services:
  airflow:
    build: .
    image: airflow-dbt:latest
    container_name: airflow
    ports:
      - "8090:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=supersecretkey
    volumes:
      - airflow_db:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/entrypoint.sh:/entrypoint.sh
      - ./dbt_project:/opt/airflow/dbt_project
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: bash /entrypoint.sh

volumes:
  airflow_db:
